### ISSUE TITLE
Trabajo futuro

### ISSUE THREAD

**Issue by alcazar90** [alcazar90/CC5205-3-proyecto#11]
Agregar sección al reporte de trabajo futuro.

- Estudiar la posibilidad de capturar la idiosincracia de una lista, su contexto y sentimiento, a través del aprendizaje de _embeddings_ sobre la letra de las canciones.  Esto podría ser un elemento relevante para que el sistema de recomendación pueda extraer canciones candidatas a recomendar utilizando más que solo las métricas de distancia sobre los _features_ de las canciones.
- Habilitar el ajuste de preferencias sobre las recomendaciones a través de interfaz de diseño que permitan a los usuarios dar _feedback_ al sistema de recomendación a través de una calificación. Esto se puede realizar a través de influir en los pesos de la recomendación (e.g. disminuir o aumentar ponderado según _feedback_), o incluir las preferencias del usuario re-entrenando el sistema. Ambas alternativas tienen ventajas y desventajas.
- Profundizar la evaluación del sistema de recomendación. Un sistema de recomendación en un contexto de producción esta lejos de utilizar una sola métrica. De hecho, en el diseño de estos sistemas, se ven involucrados distintos equipos que naturalmente tienen objetivos diferentes. Por lo tanto, estudiar cómo interactuan métricas que persiguen distintos objetivos como el aumento de ingresos (u otros KPI), criterios de cobertura de productos, o de diversidad o justicia (e.g. genero, invisibilidad de temáticas, etc), y el _trade-off_ que puede haber entre estos objetivos.
- Tratamiento al problema de "cold start", cuando tenemos un nuevo usuario, artista, o canción. Una opción es identificar por componente geográfico con el objetivo de acotar la lista de canciones más populares a nivel local. Otra estrategia a explorar es utilizar información de las sesiones de usuarios dentro de los primeros periodos de uso en a aplicación, aprender en base a esta _embeddings_, y utilizar esto para recomendar a nuevos usuarios. Una tercera opción, es utilizar información de terceros que se puede obtener en base a distintas opciones de registro (e.g. gmail, Facebook, etcétera). Esta última tiene importantes cuestionamientos en cuanto a privacidad de la información.

**Comment by dncortez** [comment]
- Incrementar el número de algoritmos de recomendación en el recomendador ponderado, de forma que adquiera más importancia la personalización y el feedback de los usuarios. Se podrían incluso incluir algoritmos completamente aleatoreos, los cuales podrían ser preferidos por usuarios que buscan conocer música distinta.
- Cronseguir bases de datos sobre retroalimentación de usuarios y cruzarlos con nuestros datos para generar mejores algoritmos de recomendación y incluirlos en el recomendador ponderado.
- Considerar utilizar variables categóricas como artista y género para los recomendadores. Adicionalmente, considerar utilizar variables más complejas como léxicas (bag of words) o que impliquen procesamiento más avanzado como obtener la letra de las canciones, de haberlo.
- Modificar el recomendador para permitir recomendación de canciones desde una lista donde las canciones tienen distinto peso. Por ejemplo, se le podría dar mayor importancia a canciones escuchadas más recientemente o a aquellas canciones que tienen más reproducciones por parte del usuario.
- Realizar encuestas y otro tipo de evaluaciones utilizando datos y listas reales para permitir una mejor y más realista evaluación de los algoritmos de recomendación para elegir los pesos iniciales.
- Determinar cuales serán las tazas de cambio de los pesos según los distintos tipos de feedback (clicks, reproducciones parciales, reproducciones completas, favoritos, agregar a lista, etc.)
