### ISSUE TITLE
Definir herramientas (Python o R + otros)

### ISSUE THREAD

**Issue by alcazar90** [alcazar90/CC5205-3-proyecto#2]
TODO: Definir herramientas, discutir breve background y expertise de cada uno.

**Comment by GianniCatBug** [comment]
Hola!, por mi parte sé bastante Python, 4 años de experiencia aprox (matplotlib, seaborn, numpy, pandas, sklearn), me manejo muy bien con jupyter notebook. También sé algo de R (lo aprendí el año pasado en un diplomado de estadística), pero soy mucho más lenta que con Python.

**Comment by alcazar90** [comment]
Genial @GianniCatBug , yo he usado ambos también, pero soy más fluido con R.

Me manejo bastante haciendo visualizaciones estáticas enfocadas en presentaciones finales (reportes/informes) con ggplot2 y tablas.

Ahora, no es necesario que usemos solo un lenguaje, podríamos modularizar las tareas y ocupar python para preprocesar los datos, análisis exploratorio en jupyter con todo el toolkit (i.e. pandas, seaborn, sklearn), las figuras para los informes con ggplot2, etcétera.

**Comment by dncortez** [comment]
Buenas! Soy ingeniero en biotecnología de la facultad de Ciencias, pero me manejo en python (4 años en laboratorio de bioinformática). También sé processing y lo he usado para hacer visualizaciones. He hecho análisis estadísticos de datos de proteínas provenientes de bacterias, tenemos un paper de eso aceptado y viene otro en camino.
https://www.biorxiv.org/content/10.1101/2021.11.05.467356v1.full
Me manejo igual en escritura científica y búsqueda bibliográfica dependiendo de cómo sea el formato final del proyecto. También por el tema de la base de datos, si nos animamos a hacer algo con biología ahí también puedo aportar bastante.

**Comment by GianniCatBug** [comment]
@dncortez  A mi me tinca el tema! :) yo trabajo con datos de clientes así que tengo complicado el tema de conseguir datos :/ . Si te pudieras conseguir datos sería genial!, sino igual voy a estar mirando kaggle por mi lado al menos.

**Comment by alcazar90** [comment]
@dncortez se te ocurre en algún tipo de aplicación para recomendar/clasificar/segmentar con los datos de proteínas de bacterias?  Yo no puedo ser más ajeno e ignorante sobre el tema, pero si tienes algo interesante, y que vez la utilidad en construir un producto de datos...genial!

**Comment by dncortez** [comment]
@alcazar90 Muchas jaja, habría que encontrar alguna forma en que se puedan analizar con las herramientas del ramo y que no sea a nivel de paper y sea interesante para todos. Igual como yo recién me estoy incorporando al data science recomendaría que fuera segunda opción por el momento. Han dado fecha límite para tener el tema? Saludos!

**Comment by CHSTR** [comment]
Hola buenas! Soy ing. informático, tengo ~3 años de experiencia con python (pytorch, numpy, matplotlib, pandas) y también me manejo con jupyter notebook. Además tengo exp en desarrollo web (por si el proyecto lo necesita). 

En lo personal prefiero python, pero me puedo adaptar a R.

Con respecto al tema del proyecto, no tengo drama si está relacionado con biología o con otra rama que no sea de mi expertiz. De todas formas estaré mirando algunos dataset's, por si encuentro algo les aviso. Saludos!

**Comment by dncortez** [comment]
Por lo que entendí en el Zoom de hoy, no recomendaría usar bases de datos de  proteína.  Son datos no estructurados.  Igual también existen bases de datos de proteínas en forma de tablas, pero creo que no se ajusta bien al foco del proyecto.
Vería si hay algo que se pueda hacer con las bases de datos de covid.

**Comment by Callpiwix** [comment]
Hola a todos, mi nombre es Felipe Callpa. Egrese de ingeniería Industrial y llevo dos años trabajando como data science. Por mi pega podría conseguir una base de todos los paquetes enviados por couriers(chilexpress-starken-etc) en el 2021. Sería una base bien grande y sucia. Nos permitiría abordar varios temas, como clasificación de couriers, comunas que más compran o predecir cuando llegan los paquetes. 
Particularmente prefiero Python, R no me desagrada. 
Abierto a todo lo que proponga el equipo!

**Comment by GianniCatBug** [comment]
A mi me tinca lo de Felipe :o @Callpiwix y te pueden pasar los datos ? claramente no necesitamos ruts ni nombres, pero dependiendo de lo que hagamos podriamos necesitar por ejemplo direccion de origen-destino (relevante para calcular distancia, y ver si eso se relaciona con el tiempo de llegada o llegada a tiempo por ejemplo)

**Comment by Callpiwix** [comment]
@GianniCatBug Si no hay problema, tengo que eliminar las columnas conflictivas. Podría generar el dataset, lo subo y ustedes me dicen si les tinca. 
Todo lo que es Github soy un poco novato pero les sigo la marcha !
