### ISSUE TITLE
Ideas para el EDA

### ISSUE THREAD

**Issue by alcazar90** [alcazar90/CC5205-3-proyecto#6]
**TODO:** Utilicemos este _issue_ para discutir ideas y artefactos para analizar los datos.

En el [README](https://github.com/alcazar90/CC5205-3-proyecto) se encuentra el _codebook_ de las tres tablas: playlist, canciones y artistas.

Una idea que encuentro interesante es explorar mapas de calor que contrasten algún atributo particular (e.g. positividad, acústica) de los _tracks_ que componen un conjunto de listas. Esto nos permite verificar si dos listas se encuentran cercanas en algún atributo y otros patrones.

Ahora una visualización que ilustra la idea (Colab con código [acá](https://colab.research.google.com/drive/1-4yyzpAYbSztH0mEkC_J1TIUlduieEVm?usp=sharing)):

Se pueden comparar un set de playlists (identificador en la vertical) y las canciones que los conforman (horizontal), ordenadas cada una de menor a mayor por el atributo `loudness`. Dado que las listas no tienen porque tener las mismas canciones (y ranking por atributo), se crea una columna identificador por este ranking que va de la canción T0 a Tn, donde n es el número de canciones que tiene cada lista. La visualización queda más estética si se compara con igual número de canciones, evitando los manchones blancos.

![heatmap_loudness](https://user-images.githubusercontent.com/14035919/159627559-5299e3db-aa11-4c2d-ac7b-9ff6834851a9.png)

Se puede generalizar la idea para todos los features respecto al mismo set de playlist:

![heatmap_features](https://user-images.githubusercontent.com/14035919/159627716-996a205e-e273-43bf-8230-018a68a27702.png)

**Comment by dncortez** [comment]
Me gusta la idea de los heatmaps, aunque lo mostraría más como histogramas. También vería preliminarmente si hay algúna combinacion de atributos que produce canciones más populares con PCA. Mañana le echaré un ojo. Porfa avisenme si alguien está haciendo exactamente lo mismo jaja.

**Comment by alcazar90** [comment]
@dncortez oka, esta interesante en lo del PCA.

Yo voy a continuar probando con varías medidas de distancias para ver qué tan parecidas son dos listas.

**Comment by dncortez** [comment]
Buenas! Creé una nueva sección en el mismo [colab](https://colab.research.google.com/drive/1-4yyzpAYbSztH0mEkC_J1TIUlduieEVm?usp=sharing#scrollTo=chdD7moHds5P) llamada "PCA features" y ahí realicé los análisis. No es mucho, pero se ve como algunas características se agrupan juntas. La mayoría de las canciones son energéticas, de volumen fuerte y no acústicas. Las canciones bailables tienden a ser más alegres y vocales. Existe una "nube" de canciones más tristes, acústicas, instrumentales y de larga duración a la que bauticé de cariño "Nube alternativa". Sorprendentemente, las canciones en menor son más bailables. De todas formas, la modalidad está uniformemente distribuida, al igual que la nota basal de la canción. Esto ultimo no debería sorprender, ya que en general las canciones se perciben de igual forma sea cual sea en la nota que esté. No así con la modalidad.
![image](https://user-images.githubusercontent.com/54562534/159823224-3a5db617-29c1-4b9c-9fae-0ec182b2eab2.png)

Les dejo todas las coloraciones. Se puede ver aca como hay algunas que parecieran ser ruido (Key), y como en otras debería ser necesario escalarlas de alguna forma ya que hay algunos valores muy extremos y en el PCA se ven como todos del mismo color (duration. No faltan las canciones de 30 minutos de prog). También me gustaría transformar "time signature", ya que en general se ve que las 4/4 están agrupadas a un lado mientras las 3/4 o 5/4 están en otro. El PCA trata los datos como que  4 está entre 3 y 5, cuando lo que sería más conveniente medir es que tan "regular" es un signature (4> 3 > 5 > 7 u otras cosas raras que podrían aparecer en el dataset full).
También me gustaría limpiar "loudness" que es casi lo mismo que energy, o incluso ambas.
![image](https://user-images.githubusercontent.com/54562534/159824758-f17b3153-5fd3-4be5-b5fd-ee29b664a60e.png)

Con esto, me gustaría proseguir viendo cómo se distribuyen las canciones considerando las playlists, ya sea viendo si las canciones similares se agrupan en las mismas playlists o usando el número de veces que una canción aparece en una playlist como un indicador de popularidad y ver si eso nos dice algo.

Also: Qué pasó con la variable popularidad? Con esa podríamos ver hartas cosas!

**Comment by Callpiwix** [comment]
Hola, hice un análisis pequeño de las correlaciones para empezar a hacernos las preguntas que proponen en el hito1. [colab ](https://colab.research.google.com/drive/1g1n3VCAYvsPqmfD3jlz4IVHW5LtOJHkd?usp=sharing)

![image](https://user-images.githubusercontent.com/94117595/160716436-61b00316-7c21-4d26-9c23-cb89ae775fa3.png)

Alguno de los insight que se me ocurrieron:

- Existe una correlación entre diferentes tipos de canciones, valance - danceability, valance - Energy y, en menor medida, valance - loudness. Esto tiene sentido, dado que las correlaciones obtenidas se relacionan con el tono alegre y movimiento que entrega la canción a la audiencia.
- Por otro lado, tenemos una correlación fuerte entre las características de cada canción como el num_albums - num_tracks, num_albums - num_artists y más. Lo que tiene sentido, dado que un albún debe normalmente tiene un sólo artista y cada albún puede tener diferente tipos de canciones.

¿Una persona que les guste canciones como mayor energía es más propensa a escuchar canciones bailables?

¿Una persona que le guste escuchar canciones positivas (valance) para motivarse en su día a día, es más propensa a escuchar canciones bailables (danceability), intensas (energy) y de decibeles altos(loudness)?

**Comment by GianniCatBug** [comment]
Hice una exploración probablemente demasiado excesiva del set de playlists XD, básicamente de todos los atributos.

[Colab](https://colab.research.google.com/drive/1_B0unCkcZuhEkO3c7ApkUbytephDUU43?usp=sharing)

Hice tanto de los atributos de la playlist en sí (que no sé en realidad si al final usemos esos datos para algo para recomendar las canciones jeje, pero igual va), y de las canciones, lo que se podía de esa tabla. También exploré los nulos (casi no hay)

Mañana veo los resultados más detenidamente, por ahora solo me dio mucha risa que dentro de las palabras más frecuentes de los nombres de las canciones estuviera "feat" XD (hay un youtuber que se burla diciendo que uno de los pasos para ser cantante famoso es hacer muchas colaboraciones jajaja).

![image](https://user-images.githubusercontent.com/15250397/161883572-f11b9050-2cd5-4d13-8082-2cc20c6dfbb9.png)

**Comment by CHSTR** [comment]
Buenas! Adjuntaré algunas imagenes sobre el análisis de los artistas-playlist y demás. Está todo en el [colab](https://colab.research.google.com/drive/1HAjICvI4BQDpqVcpMme1VEjEyHRt582t?usp=sharing) (después lo uno con lo que tiene Gianina).

Creo que mis imágenes no se ven tan bien en github D:, pero haciendo click se deberían ver mejor. Igual las subiré a la carpeta ./fig en versión fullhd4k60fps.

¿Cómo se distribuye la popularidad de los artistas?
![image](https://user-images.githubusercontent.com/31752572/161893499-1118c473-95e7-48ee-b656-63e917e95cba.png)
¿Cuáles son los géneros que más se repiten en el dataset? (TOP 50)
![image](https://user-images.githubusercontent.com/31752572/161893560-6845794f-3a82-4c90-955c-8719b70aaa9a.png)
¿Cuántos géneros tienen los artistas según spotify?
![image](https://user-images.githubusercontent.com/31752572/161893644-fa7e30dc-4960-4687-95f0-19d98fdc9f43.png)
¿Cuáles son los artistas que más se repiten? (TOP 50)
![image](https://user-images.githubusercontent.com/31752572/161893687-c1a8ae9e-4448-4e4e-ae39-5b155dfbdc5e.png)

Iré agregando otros análisis sobre los artistas en el mismo colab (o en el que estemos dejando todo).

**Comment by dncortez** [comment]
Buenas! Hice un mini cambio a una figura del Christopher para que se vean mejor los colores. Sólo le agregué 'cmap="RdBu", vmin=-1, vmax=1' a la función del heatmap.
![image](https://user-images.githubusercontent.com/54562534/162130172-bf377521-9281-42d1-a171-7325fe315638.png)

**Comment by GianniCatBug** [comment]
Hola!, se ven cachilupis @CHSTR y @Callpiwix . Faltaría que agreguen sus partes en el README :). Yo acabo de subir lo mio de playlists con los gráficos, análisis y preguntas propuestas al final.
